/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package edu.berkeley.path.model_elements_base;  
@SuppressWarnings("all")
/** * PeMS sensor (the VDS station info, rather than the sensor data). */
public class PeMSVDS extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PeMSVDS\",\"namespace\":\"edu.berkeley.path.model_elements_base\",\"doc\":\"* PeMS sensor (the VDS station info, rather than the sensor data).\",\"fields\":[]}");

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /** Creates a new PeMSVDS RecordBuilder */
  public static edu.berkeley.path.model_elements_base.PeMSVDS.Builder newBuilder() {
    return new edu.berkeley.path.model_elements_base.PeMSVDS.Builder();
  }
  
  /** Creates a new PeMSVDS RecordBuilder by copying an existing Builder */
  public static edu.berkeley.path.model_elements_base.PeMSVDS.Builder newBuilder(edu.berkeley.path.model_elements_base.PeMSVDS.Builder other) {
    return new edu.berkeley.path.model_elements_base.PeMSVDS.Builder(other);
  }
  
  /** Creates a new PeMSVDS RecordBuilder by copying an existing PeMSVDS instance */
  public static edu.berkeley.path.model_elements_base.PeMSVDS.Builder newBuilder(edu.berkeley.path.model_elements_base.PeMSVDS other) {
    return new edu.berkeley.path.model_elements_base.PeMSVDS.Builder(other);
  }
  
  /**
   * RecordBuilder for PeMSVDS instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PeMSVDS>
    implements org.apache.avro.data.RecordBuilder<PeMSVDS> {


    /** Creates a new Builder */
    private Builder() {
      super(edu.berkeley.path.model_elements_base.PeMSVDS.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(edu.berkeley.path.model_elements_base.PeMSVDS.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing PeMSVDS instance */
    private Builder(edu.berkeley.path.model_elements_base.PeMSVDS other) {
            super(edu.berkeley.path.model_elements_base.PeMSVDS.SCHEMA$);
    }

    @Override
    public PeMSVDS build() {
      try {
        PeMSVDS record = new PeMSVDS();
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
