/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package edu.berkeley.path.model_elements_base;  
@SuppressWarnings("all")
public enum RunMode { 
  HISTORICAL, LIVE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"RunMode\",\"namespace\":\"edu.berkeley.path.model_elements_base\",\"symbols\":[\"HISTORICAL\",\"LIVE\"]}");
}
