/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package edu.berkeley.path.model_elements_base;  
@SuppressWarnings("all")
public class VelocitySet extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"VelocitySet\",\"namespace\":\"edu.berkeley.path.model_elements_base\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"description\",\"type\":[\"null\",\"string\"]},{\"name\":\"projectId\",\"type\":[\"null\",\"string\"]},{\"name\":\"velocity\",\"type\":{\"type\":\"record\",\"name\":\"VelocityMap\",\"doc\":\"* Velocity on each link at a point in time\",\"fields\":[{\"name\":\"metersPerSecond\",\"type\":{\"type\":\"map\",\"values\":\"double\"},\"doc\":\"map key is linkId\",\"default\":{}}]}}]}");
  @Deprecated public java.lang.CharSequence id;
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.lang.CharSequence description;
  @Deprecated public java.lang.CharSequence projectId;
  @Deprecated public edu.berkeley.path.model_elements_base.VelocityMap velocity;

  /**
   * Default constructor.
   */
  public VelocitySet() {}

  /**
   * All-args constructor.
   */
  public VelocitySet(java.lang.CharSequence id, java.lang.CharSequence name, java.lang.CharSequence description, java.lang.CharSequence projectId, edu.berkeley.path.model_elements_base.VelocityMap velocity) {
    this.id = id;
    this.name = name;
    this.description = description;
    this.projectId = projectId;
    this.velocity = velocity;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    case 2: return description;
    case 3: return projectId;
    case 4: return velocity;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: name = (java.lang.CharSequence)value$; break;
    case 2: description = (java.lang.CharSequence)value$; break;
    case 3: projectId = (java.lang.CharSequence)value$; break;
    case 4: velocity = (edu.berkeley.path.model_elements_base.VelocityMap)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'description' field.
   */
  public java.lang.CharSequence getDescription() {
    return description;
  }

  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.CharSequence value) {
    this.description = value;
  }

  /**
   * Gets the value of the 'projectId' field.
   */
  public java.lang.CharSequence getProjectId() {
    return projectId;
  }

  /**
   * Sets the value of the 'projectId' field.
   * @param value the value to set.
   */
  public void setProjectId(java.lang.CharSequence value) {
    this.projectId = value;
  }

  /**
   * Gets the value of the 'velocity' field.
   */
  public edu.berkeley.path.model_elements_base.VelocityMap getVelocity() {
    return velocity;
  }

  /**
   * Sets the value of the 'velocity' field.
   * @param value the value to set.
   */
  public void setVelocity(edu.berkeley.path.model_elements_base.VelocityMap value) {
    this.velocity = value;
  }

  /** Creates a new VelocitySet RecordBuilder */
  public static edu.berkeley.path.model_elements_base.VelocitySet.Builder newBuilder() {
    return new edu.berkeley.path.model_elements_base.VelocitySet.Builder();
  }
  
  /** Creates a new VelocitySet RecordBuilder by copying an existing Builder */
  public static edu.berkeley.path.model_elements_base.VelocitySet.Builder newBuilder(edu.berkeley.path.model_elements_base.VelocitySet.Builder other) {
    return new edu.berkeley.path.model_elements_base.VelocitySet.Builder(other);
  }
  
  /** Creates a new VelocitySet RecordBuilder by copying an existing VelocitySet instance */
  public static edu.berkeley.path.model_elements_base.VelocitySet.Builder newBuilder(edu.berkeley.path.model_elements_base.VelocitySet other) {
    return new edu.berkeley.path.model_elements_base.VelocitySet.Builder(other);
  }
  
  /**
   * RecordBuilder for VelocitySet instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<VelocitySet>
    implements org.apache.avro.data.RecordBuilder<VelocitySet> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence name;
    private java.lang.CharSequence description;
    private java.lang.CharSequence projectId;
    private edu.berkeley.path.model_elements_base.VelocityMap velocity;

    /** Creates a new Builder */
    private Builder() {
      super(edu.berkeley.path.model_elements_base.VelocitySet.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(edu.berkeley.path.model_elements_base.VelocitySet.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing VelocitySet instance */
    private Builder(edu.berkeley.path.model_elements_base.VelocitySet other) {
            super(edu.berkeley.path.model_elements_base.VelocitySet.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = (java.lang.CharSequence) data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = (java.lang.CharSequence) data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.description)) {
        this.description = (java.lang.CharSequence) data().deepCopy(fields()[2].schema(), other.description);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.projectId)) {
        this.projectId = (java.lang.CharSequence) data().deepCopy(fields()[3].schema(), other.projectId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.velocity)) {
        this.velocity = (edu.berkeley.path.model_elements_base.VelocityMap) data().deepCopy(fields()[4].schema(), other.velocity);
        fieldSetFlags()[4] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.CharSequence getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public edu.berkeley.path.model_elements_base.VelocitySet.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public edu.berkeley.path.model_elements_base.VelocitySet.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'name' field */
    public java.lang.CharSequence getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public edu.berkeley.path.model_elements_base.VelocitySet.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'name' field */
    public edu.berkeley.path.model_elements_base.VelocitySet.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'description' field */
    public java.lang.CharSequence getDescription() {
      return description;
    }
    
    /** Sets the value of the 'description' field */
    public edu.berkeley.path.model_elements_base.VelocitySet.Builder setDescription(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.description = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'description' field has been set */
    public boolean hasDescription() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'description' field */
    public edu.berkeley.path.model_elements_base.VelocitySet.Builder clearDescription() {
      description = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'projectId' field */
    public java.lang.CharSequence getProjectId() {
      return projectId;
    }
    
    /** Sets the value of the 'projectId' field */
    public edu.berkeley.path.model_elements_base.VelocitySet.Builder setProjectId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.projectId = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'projectId' field has been set */
    public boolean hasProjectId() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'projectId' field */
    public edu.berkeley.path.model_elements_base.VelocitySet.Builder clearProjectId() {
      projectId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'velocity' field */
    public edu.berkeley.path.model_elements_base.VelocityMap getVelocity() {
      return velocity;
    }
    
    /** Sets the value of the 'velocity' field */
    public edu.berkeley.path.model_elements_base.VelocitySet.Builder setVelocity(edu.berkeley.path.model_elements_base.VelocityMap value) {
      validate(fields()[4], value);
      this.velocity = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'velocity' field has been set */
    public boolean hasVelocity() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'velocity' field */
    public edu.berkeley.path.model_elements_base.VelocitySet.Builder clearVelocity() {
      velocity = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public VelocitySet build() {
      try {
        VelocitySet record = new VelocitySet();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.description = fieldSetFlags()[2] ? this.description : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.projectId = fieldSetFlags()[3] ? this.projectId : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.velocity = fieldSetFlags()[4] ? this.velocity : (edu.berkeley.path.model_elements_base.VelocityMap) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
